# Use the specified Golang version for development
FROM golang:1.23.3 AS dev

WORKDIR /app

# Install Air for live reloading
RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

# Ensure the tmp directory exists
RUN mkdir -p /app/tmp

COPY . .

CMD ["air", "-c", ".air.toml"]