# Use the specified Golang version for production
FROM golang:1.23.3 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o service_foo .

# Minimal runtime image
FROM debian:bullseye-slim

WORKDIR /root/
COPY --from=builder /app/service_foo .

EXPOSE 8080
CMD ["./service_foo"]
